services:
  - type: web
    name: trace
    runtime: docker
    plan: free
    branch: main
    autoDeploy: true
    dockerfilePath: ./deploy/render/Dockerfile
    dockerContext: .
    healthCheckPath: /api/health

    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false